% global show_x_center show_y_center current_center pick_center enter_x enter_y go_button;

function myfunc
fig = figure('Visible','off','Color','k',...
             'NumberTitle','off','MenuBar','none',...
             'Position',[360,500,1000,305]);
              
% Create radio buttons in the button group.
bg = uibuttongroup(fig,...
                  'Title','App Modes','BackgroundColor','black',...
                  'ForegroundColor','white',...
                  'Position', [0 0 .15 .15],...
                  'SelectionChangedFcn',@bg_selection);
explore_mode = uicontrol(bg,...
               'Style','radiobutton','BackgroundColor','black',...
               'String','Explore','ForegroundColor','white',...
               'Position',[5 10 70 15]);
              
movie_mode = uicontrol(bg,...
               'Style','radiobutton','BackgroundColor','black',...
               'String','Movie','ForegroundColor','white',...
               'Position',[80 10 70 15]);
              
color_mode =uicontrol(fig,... 
                        'Style','popupmenu',...
                        'Position',[480 10 70 15],...
                        'String',{'Bright','Smooth'},...
                        'Callback',@set_color_mode);              
              
show_x_center = uicontrol(fig,...
                           'Visible','on','Style','text',...
                           'Position',[288 10 70 15],...
                           'String','x');
                        
show_y_center = uicontrol(fig,...
                           'Visible','on','Style','text',...
                           'Position',[400 10 70 15],...
                           'String','y');
                       
enter_x = uicontrol(fig,...
                    'Visible','off','Style','edit',...
                    'Position',[288 10 70 15],...
                    'Callback',@enter_x_Callback); 
                
enter_y = uicontrol(fig,...
                    'Visible','off','Style','edit',...
                    'Position',[400 10 70 15],...
                    'Callback',@enter_y_Callback); 
                
current_center = uicontrol(fig,...
                            'Visible','on','Style','text','BackgroundColor','black',...
                            'Position',[280 35 70 15],'FontWeight','bold',...
                            'ForegroundColor','white','String','Position:');
                        
plus_i = uicontrol(fig,...
                    'Visible','on','Style','text','BackgroundColor','black',...
                    'Position',[367 10 30 15],'FontWeight','bold',...                
                    'ForegroundColor','white','String','+  i');  
                
set_center = uicontrol(fig,...
                         'Visible','off','Style','text','BackgroundColor','black',...
                         'Position',[280 35 80 15],'FontWeight','bold',...
                         'ForegroundColor','white','String','Set Center:'); 
                 
zoom_level_text = uicontrol(fig,...
                        'Style','text','BackgroundColor','black',...
                        'Position',[170 10 20 15],'FontWeight','bold',...
                        'ForegroundColor','white','String','10^ '); 
                     
zoom_level = uicontrol(fig,...
                        'Style','edit','Position',[195 10 30 15],...
                        'Callback',@set_zoom_level);
                    
movie_time = uicontrol(fig,...
                        'Style','edit','Position',[235 10 30 15],...
                        'Callback',@set_movie_time); 
                
go_button = uicontrol(fig,...
                      'Visible','off','Style','pushbutton',...
                      'Position',[880 10 40 30],'String','GO!',...
                      'Callback',@go_button_Callback);

resolution = uicontrol(fig,... 
                        'Style','popupmenu',...
                        'Position',[560 10 70 15],...
                        'String',{'res1','res2','res3','etc'},...
                        'Callback',@set_resolution);
                    
resolution_text = uicontrol(fig,...
                            'Style','text','BackgroundColor','black',...
                            'Position',[540 30 80 15],...
                            'String','Set Resolution:',...
                            'ForegroundColor','white','FontWeight','bold');              

color_map = uicontrol(fig,... 
                        'Style','popupmenu',...
                        'Position',[640 10 70 15],...
                        'String',{'cmap1','cmap2','cmap3','etc'},...
                        'Callback',@set_color_map);   
                    
color_map_text = uicontrol(fig,...
                           'Style','text','BackgroundColor','black',...
                           'Position',[620 30 80 15],...
                           'String','Set Colormap:',...
                           'ForegroundColor','white','FontWeight','bold');                     
                    
depth_levels = uicontrol(fig,...
                         'Style','edit',...
                         'Position',[720 10 70 15],...
                         'Callback',@enter_depth_levels); 
                     
depth_levels_text = uicontrol(fig,...
                               'Style','text','BackgroundColor','black',...
                               'Position',[710 30 80 15],...
                               'String','Set Depth Levels:',...
                               'ForegroundColor','white','FontWeight','bold'); 
                     
max_colors = uicontrol(fig,...
                        'Style','edit',...
                        'Position',[800 10 70 15],...
                        'Callback',@enter_max_colors); 
                    
max_colors_text = uicontrol(fig,...
                               'Style','text','BackgroundColor','black',...
                               'Position',[790 30 80 15],...
                               'String','Set Number of Colors:',...
                               'ForegroundColor','white','FontWeight','bold');                     

ha = axes('Units','pixels','Box','off','XTick',[],'YTick',[],'Position',[0,60,480,270]);
              
  
% Initialize the UI.
% Change units to normalized so components resize automatically.
fig.Units = 'normalized';
ha.Units = 'normalized';
bg.Units = 'normalized';
color_mode.Units = 'normalized'; 
plus_i.Units='normalized'; 
movie_mode.Units = 'normalized';
explore_mode.Units = 'normalized';
show_x_center.Units = 'normalized';
show_y_center.Units = 'normalized';
current_center.Units = 'normalized';
set_center.Units = 'normalized';
enter_x.Units = 'normalized';
enter_y.Units = 'normalized';
go_button.Units = 'normalized';
resolution.Units = 'normalized';
color_map.Units = 'normalized'; 
depth_levels.Units = 'normalized'; 
depth_levels_text.Units = 'normalized'; 
max_colors.Units = 'normalized'; 
max_colors_text.Units = 'normalized'; 
resolution_text.Units = 'normalized'; 
color_map_text.Units = 'normalized'; 
zoom_level.Units = 'normalized'; 
zoom_level_text.Units = 'normalized'; 
movie_time.Units = 'normalized'; 

% Assign the a name to appear in the window title.
fig.Name = 'Preliminary Mandelbrot App';


% Move the window to the center of the screen.
movegui(fig,'center')

% Make the window visible.
fig.Visible = 'on';


%%%%%% Program the Functionality of Features %%%%%%%

% Radio Button Functionality 

    function bg_selection(source,eventdata)
      % Determine the selected data set.
      % Set current data to the selected data set.
      switch get(eventdata.NewValue,'String')
          case 'Explore' 
             current_center.Visible='on'; 
             show_x_center.Visible='on'; 
             show_y_center.Visible='on'; 
             set_center.Visible='off';
             enter_x.Visible='off'; 
             enter_y.Visible='off'; 
             go_button.Visible='off'; 
          case 'Movie'
             set_center.Visible='on';
             enter_x.Visible='on'; 
             enter_y.Visible='on'; 
             go_button.Visible='on'; 
             current_center.Visible='off'; 
             show_x_center.Visible='off'; 
             show_y_center.Visible='off'; 
      end
    end



end